#!/bin/bash -e

BASE_DIR=$(dirname $0)
ROOT_DIR=${BASE_DIR}/root

JAR_DIR=${ROOT_DIR}/opt/logstash

mkdir -p $JAR_DIR

JAR=${JAR_DIR}/logstash.jar

if [ ! -e $JAR ]
then
	wget --no-check-certificate --output-document $JAR https://logstash.objects.dreamhost.com/release/logstash-1.1.13-flatjar.jar
fi

mkdir -p ${ROOT_DIR}/var/log/logstash

sudo chown -R 0:0 ${ROOT_DIR}

fpm -s dir -t deb -C ${ROOT_DIR} --name logstash --version 1.1.13 .
